#!C:/Users/steve/anaconda3/envs/cs412f25/python.exe
"""
approx_vs_augmented_plots.py

Reads approx_vs_augmented.csv (generated by run_both_approx.sh)
and produces two plots:

1) runtime_comparison.png
   - X axis: input size (number of cities)
   - Y axis: runtime in seconds
   - Two curves: approx_runtime, augmented_runtime

2) cost_comparison.png
   - X axis: input size
   - Y axis: tour cost
   - Two curves: approx_cost, augmented_cost
"""

import csv
import matplotlib
# Use non-interactive backend so this works on headless setups too
matplotlib.use("Agg")
import matplotlib.pyplot as plt

CSV_FILE = "approx_vs_augmented.csv"

test_cases = []
input_sizes = []
approx_runtimes = []
augmented_runtimes = []
approx_costs = []
augmented_costs = []



def parse_cost_and_n(result_str: str):
    """
    result_str looks like:
        '6.0000 b a b'
        '3026.0000 rf cq nh ...'
    First token is cost; remaining tokens are labels (path with start repeated).
    We infer input size as the number of unique labels in the path.
    """
    tokens = result_str.strip().split()
    if not tokens:
        return 0.0, 0
    cost = float(tokens[0])
    labels = tokens[1:]
    n = len(set(labels)) 
    return cost, n


with open(CSV_FILE, newline="") as f:
    reader = csv.DictReader(f)
    for row in reader:
        approx_result = row["approx_result"]
        augmented_result = row["augmented_result"]

        approx_cost, n1 = parse_cost_and_n(approx_result)
        augmented_cost, n2 = parse_cost_and_n(augmented_result)

        # They should match; if not, just take max to be safe
        n = max(n1, n2)

        # ---------- CHANGE: skip "earlier" / small cases entirely ----------
        # Only keep test cases we actually care about for plotting/annotation.
        # Here: only n >= 14 survive (the ones you annotate in the for-loops).
        if n < 14:
            continue
        # --------------------------------------------------------------

        tc = row["test_case"]
        test_cases.append(tc)
        input_sizes.append(n)
        approx_costs.append(approx_cost)
        augmented_costs.append(augmented_cost)

        approx_runtimes.append(float(row["approx_time"]))
        augmented_runtimes.append(float(row["augmented_time"]))

# Sort by input size so the lines don't zig-zag
data = list(
    zip(
        input_sizes,
        test_cases,
        approx_runtimes,
        augmented_runtimes,
        approx_costs,
        augmented_costs,
    )
)
data.sort(key=lambda x: x[0])

input_sizes, test_cases, approx_runtimes, augmented_runtimes, approx_costs, augmented_costs = zip(
    *data
)

# ---------- Plot 1: Runtime comparison ----------
plt.figure(figsize=(8, 5))
plt.plot(input_sizes, approx_runtimes, marker="o", label="Approx runtime")
plt.plot(input_sizes, augmented_runtimes, marker="o", label="Augmented runtime")

# Annotate the augmented runtime points for larger instances
# NOTE: now *only* n >= 14 exist, but we still treat 14 vs >=15 differently.
for x, rt, name in zip(input_sizes, augmented_runtimes, test_cases):
    if n < 14:
        continue
    elif x == 14:
        # Style for the n=14 case
        plt.annotate(
            name,
            (x, rt),
            textcoords="offset points",
            xytext=(-5, 5),
            fontsize=8,
            ha="left",
            rotation=20
        )
    elif x >= 15:
        # Style for all strictly larger cases
        plt.annotate(
            name,
            (x, rt),
            textcoords="offset points",
            xytext=(-5, 5),
            fontsize=8,
            ha="right",
        )

plt.xlabel("Input size (number of cities)")
plt.ylabel("Runtime (seconds)")
plt.title("Approx vs Augmented Runtime")
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.savefig("a_a_runtime_comparison.png", dpi=200)

# ---------- Plot 2: Cost comparison ----------
plt.figure(figsize=(8, 5))
plt.plot(input_sizes, approx_costs, marker="o", label="Approx cost")
plt.plot(input_sizes, augmented_costs, marker="o", label="Augmented cost")

# Optionally annotate larger instances — same idea as above
for x, ac, pe, name in zip(input_sizes, approx_costs, augmented_costs, test_cases):
    if n < 14:
        continue
    elif x == 14:
        plt.annotate(
            name,
            (x, pe),
            textcoords="offset points",
            xytext=(5, 5),
            fontsize=8,
            ha="left",
            # rotation=35
        )
    elif x >= 15:
        plt.annotate(
            name,
            (x, pe),
            textcoords="offset points",
            xytext=(5, 5),
            fontsize=8,
            ha="right",
        )

plt.xlabel("Input size (number of cities)")
plt.ylabel("Tour cost")
plt.title("Approx vs Augmented Solution Quality")
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.savefig("a_a_cost_comparison.png", dpi=200)

print("Saved a_a_runtime_comparison.png and a_a_cost_comparison.png")
