#!C:/Users/steve/anaconda3/envs/cs412f25/python.exe
"""
old_vs_new_plots.py

Reads old_vs_new_results.csv (generated by compute_old_vs_new.sh)
and produces:

1) old_vs_new_runtime.png
   - X axis: input size (number of cities)
   - Y axis: runtime in seconds
   - Two curves: old_runtime (original), new_runtime (Part E)

2) old_vs_new_cost.png
   - X axis: input size (number of cities)
   - Y axis: tour cost
   - Two curves: old_cost (original), new_cost (Part E)
"""

import csv
import matplotlib

# Use non-interactive backend so this works on headless setups too
matplotlib.use("Agg")
import matplotlib.pyplot as plt

CSV_FILE = "old_vs_new_results.csv"

test_cases = []
input_sizes = []
old_runtimes = []
new_runtimes = []
old_costs = []
new_costs = []

# Read CSV
with open(CSV_FILE, newline="") as f:
    reader = csv.DictReader(f)
    for row in reader:
        # Skip incomplete rows if any
        needed = [
            "test_case",
            "input_size",
            "old_runtime",
            "new_runtime",
            "old_cost",
            "new_cost",
        ]
        if any(row[k] is None or row[k].strip() == "" for k in needed):
            print("Skipping incomplete row:", row)
            continue

        test_cases.append(row["test_case"])
        n = int(row["input_size"])
        input_sizes.append(n)
        old_runtimes.append(float(row["old_runtime"]))
        new_runtimes.append(float(row["new_runtime"]))
        old_costs.append(float(row["old_cost"]))
        new_costs.append(float(row["new_cost"]))

# Sort by input size so lines don’t zig-zag if files are unordered
data = list(
    zip(
        input_sizes,
        test_cases,
        old_runtimes,
        new_runtimes,
        old_costs,
        new_costs,
    )
)
data.sort(key=lambda x: x[0])

(
    input_sizes,
    test_cases,
    old_runtimes,
    new_runtimes,
    old_costs,
    new_costs,
) = zip(*data)

# ---------- Plot 1: Runtime comparison ----------
plt.figure(figsize=(8, 5))
plt.plot(input_sizes, old_runtimes, marker="o", label="Original runtime")
plt.plot(input_sizes, new_runtimes, marker="o", label="Part E runtime")

for x, rt, name in zip(input_sizes, new_runtimes, test_cases):
    # lightly annotate larger instances for context
    if x >= 10:
        plt.annotate(
            name,
            (x, rt),
            textcoords="offset points",
            xytext=(5, 5),
            fontsize=8,
            ha="right",
        )

plt.xlabel("Input size (number of cities)")
plt.ylabel("Runtime (seconds)")
plt.title("Original vs Part E Runtime")
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.savefig("old_vs_new_runtime.png", dpi=200)

# ---------- Plot 2: Cost comparison ----------
plt.figure(figsize=(8, 5))
plt.plot(input_sizes, old_costs, marker="o", label="Original cost")
plt.plot(input_sizes, new_costs, marker="o", label="Part E cost")

for x, c, name in zip(input_sizes, new_costs, test_cases):
    if x >= 10:
        plt.annotate(
            name,
            (x, c),
            textcoords="offset points",
            xytext=(5, 5),
            fontsize=8,
            ha="right",
        )

plt.xlabel("Input size (number of cities)")
plt.ylabel("Tour cost")
plt.title("Original vs Part E Solution Quality")
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.savefig("old_vs_new_cost.png", dpi=200)

print("Saved old_vs_new_runtime.png and old_vs_new_cost.png")
