#!C:/Users/steve/anaconda3/envs/cs412f25/python.exe
"""
all_three_plots.py

Reads all_three_results.csv (generated by compute_all_three_wallclock.sh)
and produces two plots:

1) all_runtime_comparison.png
   - X axis: input size (number of cities)
   - Y axis: runtime in seconds
   - Three curves: exact_runtime, approx_runtime, aug_runtime

2) all_cost_comparison.png
   - X axis: input size
   - Y axis: tour cost
   - Three curves: exact_cost, approx_cost, aug_cost
"""

import csv
import matplotlib

# Use non-interactive backend so this works on headless setups too
matplotlib.use("Agg")
import matplotlib.pyplot as plt

CSV_FILE = "all_three_results.csv"

test_cases = []
input_sizes = []
exact_runtimes = []
approx_runtimes = []
aug_runtimes = []
exact_costs = []
approx_costs = []
aug_costs = []

with open(CSV_FILE, newline="") as f:
    reader = csv.DictReader(f)
    for row in reader:
        # Skip any row with missing numeric fields to avoid float('') errors
        needed = [
            "input_size",
            "exact_runtime",
            "approx_runtime",
            "aug_runtime",
            "exact_cost",
            "approx_cost",
            "aug_cost",
        ]
        if any(row[k] is None or row[k].strip() == "" for k in needed):
            print("Skipping incomplete row:", row)
            continue

        test_cases.append(row["test_case"])
        n = int(row["input_size"])
        input_sizes.append(n)

        exact_runtimes.append(float(row["exact_runtime"]))
        approx_runtimes.append(float(row["approx_runtime"]))
        aug_runtimes.append(float(row["aug_runtime"]))

        exact_costs.append(float(row["exact_cost"]))
        approx_costs.append(float(row["approx_cost"]))
        aug_costs.append(float(row["aug_cost"]))

# Sort by input size so the lines don't zig-zag
data = list(
    zip(
        input_sizes,
        test_cases,
        exact_runtimes,
        approx_runtimes,
        aug_runtimes,
        exact_costs,
        approx_costs,
        aug_costs,
    )
)
data.sort(key=lambda x: x[0])

(
    input_sizes,
    test_cases,
    exact_runtimes,
    approx_runtimes,
    aug_runtimes,
    exact_costs,
    approx_costs,
    aug_costs,
) = zip(*data)

# ---------- Plot 1: Runtime comparison ----------
plt.figure(figsize=(8, 5))
plt.plot(input_sizes, exact_runtimes, marker="o", label="Exact runtime")
plt.plot(input_sizes, approx_runtimes, marker="o", label="Approx runtime")
plt.plot(input_sizes, aug_runtimes, marker="o", label="Augmented runtime")

# Annotate the EXACT runtime points only (to keep clutter down)
for x, rt, name in zip(input_sizes, exact_runtimes, test_cases):
    if x >= 12:
        plt.annotate(
            name,
            (x, rt),
            textcoords="offset points",
            xytext=(-5, 5),
            fontsize=8,
            ha="right",
        )
    elif x >= 10:
        plt.annotate(
            name,
            (x, rt),
            textcoords="offset points",
            xytext=(-5, 5),
            fontsize=8,
            ha="right",
            rotation=-25,
        )

plt.xlabel("Input size (number of cities)")
plt.ylabel("Runtime (seconds)")
plt.title("Exact vs Approx vs Augmented Runtime")
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.savefig("all_runtime_comparison.png", dpi=200)

# ---------- Plot 2: Cost comparison ----------
plt.figure(figsize=(8, 5))
plt.plot(input_sizes, exact_costs, marker="o", label="Exact cost")
plt.plot(input_sizes, approx_costs, marker="o", label="Approx cost")
plt.plot(input_sizes, aug_costs, marker="o", label="Augmented cost")

# Optionally annotate each point with test_case name
for x, ec, ac, agc, name in zip(
    input_sizes, exact_costs, approx_costs, aug_costs, test_cases
):
    # Only label bigger instances to avoid clutter, tweak as needed
    if (x >= 5 and x < 10) or x > 10:
        plt.annotate(
            name,
            (x, agc),
            textcoords="offset points",
            xytext=(5, 5),
            fontsize=8,
            ha="right",
        )
    elif x == 10:
        plt.annotate(
            name,
            (x, agc),
            textcoords="offset points",
            xytext=(5, 5),
            fontsize=8,
            ha="center",
        )

plt.xlabel("Input size (number of cities)")
plt.ylabel("Tour cost")
plt.title("Exact vs Approx vs Augmented Solution Quality")
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.savefig("all_cost_comparison.png", dpi=200)

print("Saved all_runtime_comparison.png and all_cost_comparison.png")
