#!C:/Users/steve/anaconda3/envs/cs412f25/python.exe
"""
approx_vs_exact_plots.py

Reads approx_vs_exact_results.csv (generated by compute_approx_wallclock.sh)
and produces two plots:

1) runtime_comparison.png
   - X axis: input size (number of cities)
   - Y axis: runtime in seconds
   - Two curves: exact_runtime, approx_runtime

2) cost_comparison.png
   - X axis: input size
   - Y axis: tour cost
   - Two curves: exact_cost, approx_cost
"""

import csv
import matplotlib
# Use non-interactive backend so this works on headless setups too
matplotlib.use("Agg")
import matplotlib.pyplot as plt

CSV_FILE = "approx_vs_exact_results.csv"

test_cases = []
input_sizes = []
exact_runtimes = []
approx_runtimes = []
exact_costs = []
approx_costs = []

with open(CSV_FILE, newline="") as f:
    reader = csv.DictReader(f)
    for row in reader:
        test_cases.append(row["test_case"])
        n = int(row["input_size"])
        input_sizes.append(n)
        exact_runtimes.append(float(row["exact_runtime"]))
        approx_runtimes.append(float(row["approx_runtime"]))
        exact_costs.append(float(row["exact_cost"]))
        approx_costs.append(float(row["approx_cost"]))

# Sort by input size so the lines don't zig-zag
data = list(zip(input_sizes, test_cases, exact_runtimes, approx_runtimes, exact_costs, approx_costs))
data.sort(key=lambda x: x[0])

input_sizes, test_cases, exact_runtimes, approx_runtimes, exact_costs, approx_costs = zip(*data)

# ---------- Plot 1: Runtime comparison ----------
plt.figure(figsize=(8, 5))
plt.plot(input_sizes, exact_runtimes, marker="o", label="Exact runtime")
plt.plot(input_sizes, approx_runtimes, marker="o", label="Approx runtime")

# Annotate the EXACT runtime points only
for x, rt, name in zip(input_sizes, exact_runtimes, test_cases):
    if x >= 12:
        plt.annotate(
            name,
            (x, rt),
            textcoords="offset points",
            xytext=(-5, 5),
            fontsize=8,
            ha="right"
        )
    elif x >= 10:
        plt.annotate(
            name,
            (x, rt),
            textcoords="offset points",
            xytext=(-5, 5),
            fontsize=8,
            ha="right",
            rotation=-25
        )

plt.xlabel("Input size (number of cities)")
plt.ylabel("Runtime (seconds)")
plt.title("Exact vs Approx Runtime")
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.savefig("runtime_comparison.png", dpi=200)

# ---------- Plot 2: Cost comparison ----------
plt.figure(figsize=(8, 5))
plt.plot(input_sizes, exact_costs, marker="o", label="Exact cost")
plt.plot(input_sizes, approx_costs, marker="o", label="Approx cost")

# Optionally annotate each point with test_case name
for x, ec, ac, name in zip(input_sizes, exact_costs, approx_costs, test_cases):
    # Only label bigger instances to avoid clutter, tweak as needed
    if x >= 5 and x < 10 or x > 10:
        plt.annotate(name, (x, ac), textcoords="offset points", xytext=(5, 5), fontsize=8, ha="right")
        # rotation=-25)
    elif x == 10:
        plt.annotate(name, (x, ac), textcoords="offset points", xytext=(5, 5), fontsize=8, ha="center")


plt.xlabel("Input size (number of cities)")
plt.ylabel("Tour cost")
plt.title("Exact vs Approx Solution Quality")
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.savefig("cost_comparison.png", dpi=200)

print("Saved runtime_comparison.png and cost_comparison.png")
